packages:
  - 'examples/*'
  - 'examples/*/packages/*'

catalog:
  '@types/minimist': 1.2.5
  '@types/node': 22.17.0
  '@vitest/coverage-v8': 4.1.7
  aidly: 1.37.0
  chokidar: 5.0.0
  conditional-export: 1.1.0
  execa: 9.6.1
  husky: 9.1.7
  lint-staged: 17.0.5
  minimist: 1.2.8
  postcss: 8.5.15
  prettier: 3.8.3
  rimraf: 6.1.3
  tsdown: 0.22.0
  typescript: 6.0.3
  unrun: 0.3.0
  vite: 8.0.14
  vitest: 4.1.7
